name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update package version
        run: npm version $VERSION --no-git-tag-version

      - name: Build package
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Calculate SHA
        id: sha
        run: |
          TARBALL_URL="https://registry.npmjs.org/@chengche/mcp-cli-manager/-/mcp-cli-manager-${VERSION}.tgz"
          curl -L $TARBALL_URL -o package.tgz
          echo "SHA=$(shasum -a 256 package.tgz | cut -d ' ' -f 1)" >> $GITHUB_ENV

      - name: Checkout tap repository
        uses: actions/checkout@v4
        with:
          repository: crayon3shawn/homebrew-tap
          token: ${{ secrets.TAP_PAT }}
          path: homebrew-tap

      - name: Update Homebrew Formula
        run: |
          VERSION=${{ env.VERSION }}
          SHA=${{ env.SHA }}
          
          mkdir -p homebrew-tap/Formula
          cat > homebrew-tap/Formula/mcp-cli-manager.rb << EOL
          class McpCliManager < Formula
            desc "A CLI tool for managing MCP projects"
            homepage "https://github.com/crayon3shawn/mcp-cli-manager"
            url "https://registry.npmjs.org/@chengche/mcp-cli-manager/-/mcp-cli-manager-${VERSION}.tgz"
            sha256 "${SHA}"
            license "MIT"

            depends_on "node"

            def install
              system "npm", "install", *Language::Node.std_npm_install_args(libexec)
              bin.install_symlink Dir["#{libexec}/bin/*"]
            end

            test do
              assert_match "mcp-cli-manager", shell_output("#{bin}/mcp --version")
            end
          end
          EOL

      - name: Commit and push formula changes
        run: |
          cd homebrew-tap
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add Formula/mcp-cli-manager.rb
          git commit -m "chore: update formula to v${{ env.VERSION }}"
          git push 