name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build packages
      run: pnpm build

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        body: |
          Changes in this Release:
          ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to NPM
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
        pnpm publish -r --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Get SHA256
      id: sha256
      run: |
        curl -sL https://registry.npmjs.org/mcp-cli-manager/-/mcp-cli-manager-1.1.0.tgz | sha256sum | cut -d' ' -f1 > sha256.txt
        echo "sha256=$(cat sha256.txt)" >> $GITHUB_OUTPUT

    - name: Update Homebrew Formula
      uses: peter-evans/create-or-update-package@v2
      with:
        repository-name: crayon3shawn/homebrew-tap
        package-name: mcp-cli-manager
        formula-name: mcp-cli-manager
        formula: |
          class McpCliManager < Formula
            desc "CLI tool for managing Model Context Protocol (MCP) servers"
            homepage "https://github.com/crayon3shawn/mcp-cli-manager"
            url "https://registry.npmjs.org/mcp-cli-manager/-/mcp-cli-manager-1.1.0.tgz"
            sha256 "${{ steps.sha256.outputs.sha256 }}"
            license "MIT"

            depends_on "node"

            def install
              system "npm", "install", *Language::Node.std_npm_install_args(libexec)
              bin.install_symlink Dir["#{libexec}/bin/*"]
            end

            test do
              system "#{bin}/mcp", "--version"
            end
          end
        commit-message: "mcp-cli-manager 1.1.0"
        branch: mcp-cli-manager-1.1.0
        delete-branch: true
        title: "mcp-cli-manager 1.1.0"
        body: |
          - [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
          - [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
          - [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
          - [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
          - [x] Does your build pass `brew audit --new <formula>`, where `<formula>` is the name of the formula you're submitting? 