name: Update Homebrew

on:
  release:
    types: [published]

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Checkout homebrew-tap
        uses: actions/checkout@v3
        with:
          repository: crayon3shawn/homebrew-tap
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-tap

      - name: Update formula
        working-directory: homebrew-tap
        run: |
          cat > Formula/mcp-cli-manager.rb << EOL
          class McpCliManager < Formula
            desc "A command-line tool for managing Model Context Protocol (MCP) servers"
            homepage "https://github.com/crayon3shawn/mcp-cli-manager"
            url "https://github.com/crayon3shawn/mcp-cli-manager/archive/v${VERSION}.tar.gz"
            sha256 "$(curl -sL https://github.com/crayon3shawn/mcp-cli-manager/archive/v${VERSION}.tar.gz | sha256sum | cut -d' ' -f1)"
            version "${VERSION}"
            
            depends_on "node"
            
            def install
              system "npm", "install", *Language::Node.std_npm_install_args(libexec)
              bin.install_symlink Dir["#{libexec}/bin/*"]
            end
            
            test do
              system "#{bin}/mcp", "--version"
            end
          end
          EOL

      - name: Commit and push changes
        working-directory: homebrew-tap
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/mcp-cli-manager.rb
          git commit -m "update mcp-cli-manager to ${VERSION}"
          git push 